apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - postgres.yaml
secretGenerator:
  - name: postgres-cred
    literals:
      - password=postgres123
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nginx-deployment
