apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - config.yaml

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: nginx-deployment
