apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: app_name
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: log_level
